#!/usr/bin/env bash
# script that will display information about subdomains

# Function to check subdomains
subdomain_checker() {
  local domain="$1"
  local subdomain="$2"

  if [ -z "$subdomain" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
  else
    subdomains=("$subdomain")
  fi

  for sub in "${subdomains[@]}"; do
    result=$(dig "$sub.$domain" +short)

    if [ -z "$result" ]; then
      echo "The subdomain $sub is not configured or does not exist."
    else
      # $(dig "$sub.$domain" | grep -m1 "IN" | awk '{print $4}') = A record
      echo "The subdomain $sub is a A record and points to $result"
    fi
  done
}

# Extract domain and subdomain from parameters
domain="$1"
subdomain="$2"

# Call the check_subdomain function
subdomain_checker "$domain" "$subdomain"
