#!/usr/bin/env bash
#script that configures a new Ubuntu machine with the following:
# Install nginx on your web-01 server
# Nginx should be listening on port 80
# When querying Nginx at its root / with a GET request
# (requesting a page) using curl, it must return a page that
# contains the string Hello World!

sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir -p /var/www/html
echo "Hello World!" > /var/www/html/index.html
cat  > /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    server_name localhost;

    location / {
        root   /var/www/html;
        index   index.html;
    }
}
EOF
service nginx restart
