#!/usr/bin/env bash
#Configure your Nginx server to have a custom 404 page 

sudo apt-get -y update
sudo apt-get -y install nginx

sudo mkdir -p /var/www/html
sudo echo "Hello World!" | sudo tee /var/www/html/index.html

redirection_rule="\\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

sudo sed -i "54i $redirection_rule" /etc/nginx/sites-available/default

sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
sudo sed -i "54i \\rewrite ^/xyz error_page 404 /custom_404.html" /etc/nginx/sites-available/default 

service nginx restart
