#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server

sudo apt-get update
sudo apt-get install haproxy=2.0.\*

sudo echo 'ENABLED=1' | sudo tee /etc/default/haproxy

# Configure HAProxy by appending a frontend and backend configuration to /etc/haproxy/haproxy.cfg
sudo sed -i "$ a\
frontend load_balancer\n\
\tbind *:80\n\
\tmode http\n\
\tdefault_backend web_servers\n\
\n\
backend web_servers\n\
\tbalance roundrobin\n\
\tserver 271576-web-01 54.227.200.118:80\n\
\tserver 271576-web-02 34.224.95.92:80" /etc/haproxy/haproxy.cfg

# Restart the HAProxy service
sudo service haproxy restart
